###
GET {{host}}/user

###
GET {{host}}/user/1

###
POST {{host}}/user
Content-Type: application/json

{
  "userName": "이지은",
  "email": "aaa@bbb.com",
  "password": "a123"
}

###
DELETE {{host}}/user/1

###
GET {{host}}/todo/

###
POST {{host}}/todo
Content-Type: application/json

{
"todo": "adfdjklfa",
  "userId": 1
}

###
POST {{host}}/test

